# Arquivo de Configuração de Tema do Streamlit
# .streamlit/config.toml

[theme]

# Cor primária para elementos interativos
primaryColor="#f63366"

# Cor de fundo principal da aplicação
backgroundColor="#0E1117"

# Cor de fundo para barras laterais e outros elementos secundários
secondaryBackgroundColor="#262730"

# Cor do texto principal
textColor="#FAFAFA"

# Tipo de fonte a ser usada
font="sans serif"
